name: Ejecutar Scraper Dios
on:
  schedule:
    - cron: '0 8 * * *' # Corre a las 8 AM diario
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar Python y Chrome
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Instalar Dependencias
        run: |
          pip install pandas scikit-learn numpy selenium webdriver-manager
      - name: Ejecutar Scraper
        run: python script_dios.py
      - name: Commit de Resultados
        run: |
          git config --global user.name 'Scraper-Bot'
          git config --global user.email 'bot@dios.t'
          git add data.json
          git commit -m "üîç Datos frescos extra√≠dos" || exit 0
          git push
