name: Scraper Dios-T Autom√°tico
on:
  schedule:
    - cron: '0 9 * * *' # Se ejecuta a las 9 AM todos los d√≠as
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar Python y Selenium
        run: |
          pip install pandas scikit-learn numpy selenium webdriver-manager
      - name: Ejecutar Scraper
        run: python script_dios.py
      - name: Guardar en Web
        run: |
          git config --global user.name 'Dios-T-Bot'
          git config --global user.email 'bot@dios.t'
          git add data.json
          git commit -m "üîç Actualizaci√≥n Autom√°tica: Datos del Scraper" || exit 0
          git push
